// edited <linux/keyboard.h>
/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#if __linux__
using System.Diagnostics.Contracts;

namespace linux {
#pragma warning disable CS8981
    static class keyboard {
    
        public const byte KG_SHIFT = 0;
        public const byte KG_CTRL =  2;
        public const byte KG_ALT = 3;
        public const byte KG_ALTGR = 1;
        public const byte KG_SHIFTL = 4;
        public const byte KG_KANASHIFT = 4;
        public const byte KG_SHIFTR = 5;
        public const byte KG_CTRLL = 6;
        public const byte KG_CTRLR = 7;
        public const byte KG_CAPSSHIFT = 8;

        public const byte NR_SHIFT = 9;

        public const ushort NR_KEYS = 256;
        public const ushort MAX_NR_KEYMAPS = 256;
        /* This means 128Kb if all keymaps are allocated. Only the superuser
        may increase the number of keymaps beyond MAX_NR_OF_USER_KEYMAPS. */
        public const ushort MAX_NR_OF_USER_KEYMAPS = 256; /* should be at least 7 */


        public const ushort MAX_NR_FUNC = 256; /* max nr of strings assigned to keys */

        public const byte KT_LATIN = 0; /* we depend on this being zero */
        public const byte KT_FN = 1;
        public const byte KT_SPEC = 2;
        public const byte KT_PAD = 3;
        public const byte KT_DEAD = 4;
        public const byte KT_CONS = 5;
        public const byte KT_CUR = 6;
        public const byte KT_SHIFT = 7;
        public const byte KT_META = 8;
        public const byte KT_ASCII = 9;
        public const byte KT_LOCK = 10;
        public const byte KT_LETTER = 11; /* symbol that can be acted upon by CapsLock */
        public const byte KT_SLOCK = 12;
        public const byte KT_DEAD2 = 13;
        public const byte KT_BRL = 14;

        [Pure]
        public static ushort K(byte t, byte v) { return (ushort)((((ushort)t)<<8)|(v)); }
        [Pure]
        public static byte KTYP(short x) { return (byte)((x) >> 8); }
        [Pure]
        public static byte KVAL(short x) { return (byte)((x) & 0xff); }

        public const ushort K_F1 = ((((ushort)KT_FN)<<8)|0);
        public const ushort K_F2 = ((((ushort)KT_FN)<<8)|1);
        public const ushort K_F3 = ((((ushort)KT_FN)<<8)|2);
        public const ushort K_F4 = ((((ushort)KT_FN)<<8)|3);
        public const ushort K_F5 = ((((ushort)KT_FN)<<8)|4);
        public const ushort K_F6 = ((((ushort)KT_FN)<<8)|5);
        public const ushort K_F7 = ((((ushort)KT_FN)<<8)|6);
        public const ushort K_F8 = ((((ushort)KT_FN)<<8)|7);
        public const ushort K_F9 = ((((ushort)KT_FN)<<8)|8);
        public const ushort K_F10 = ((((ushort)KT_FN)<<8)|9);
        public const ushort K_F11 = ((((ushort)KT_FN)<<8)|10);
        public const ushort K_F12 = ((((ushort)KT_FN)<<8)|11);
        public const ushort K_F13 = ((((ushort)KT_FN)<<8)|12);
        public const ushort K_F14 = ((((ushort)KT_FN)<<8)|13);
        public const ushort K_F15 = ((((ushort)KT_FN)<<8)|14);
        public const ushort K_F16 = ((((ushort)KT_FN)<<8)|15);
        public const ushort K_F17 = ((((ushort)KT_FN)<<8)|16);
        public const ushort K_F18 = ((((ushort)KT_FN)<<8)|17);
        public const ushort K_F19 = ((((ushort)KT_FN)<<8)|18);
        public const ushort K_F20 = ((((ushort)KT_FN)<<8)|19);
        public const ushort K_FIND = ((((ushort)KT_FN)<<8)|20);
        public const ushort K_INSERT = ((((ushort)KT_FN)<<8)|21);
        public const ushort K_REMOVE = ((((ushort)KT_FN)<<8)|22);
        public const ushort K_SELECT = ((((ushort)KT_FN)<<8)|23);
        public const ushort K_PGUP = ((((ushort)KT_FN)<<8)|24); /* PGUP is a synonym for PRIOR */
        public const ushort K_PGDN = ((((ushort)KT_FN)<<8)|25); /* PGDN is a synonym for NEXT */
        public const ushort K_MACRO  = ((((ushort)KT_FN)<<8)|26);
        public const ushort K_HELP = ((((ushort)KT_FN)<<8)|27);
        public const ushort K_DO = ((((ushort)KT_FN)<<8)|28);
        public const ushort K_PAUSE  = ((((ushort)KT_FN)<<8)|29);
        public const ushort K_F21 = ((((ushort)KT_FN)<<8)|30);
        public const ushort K_F22 = ((((ushort)KT_FN)<<8)|31);
        public const ushort K_F23 = ((((ushort)KT_FN)<<8)|32);
        public const ushort K_F24 = ((((ushort)KT_FN)<<8)|33);
        public const ushort K_F25 = ((((ushort)KT_FN)<<8)|34);
        public const ushort K_F26 = ((((ushort)KT_FN)<<8)|35);
        public const ushort K_F27 = ((((ushort)KT_FN)<<8)|36);
        public const ushort K_F28 = ((((ushort)KT_FN)<<8)|37);
        public const ushort K_F29 = ((((ushort)KT_FN)<<8)|38);
        public const ushort K_F30 = ((((ushort)KT_FN)<<8)|39);
        public const ushort K_F31 = ((((ushort)KT_FN)<<8)|40);
        public const ushort K_F32 = ((((ushort)KT_FN)<<8)|41);
        public const ushort K_F33 = ((((ushort)KT_FN)<<8)|42);
        public const ushort K_F34 = ((((ushort)KT_FN)<<8)|43);
        public const ushort K_F35 = ((((ushort)KT_FN)<<8)|44);
        public const ushort K_F36 = ((((ushort)KT_FN)<<8)|45);
        public const ushort K_F37 = ((((ushort)KT_FN)<<8)|46);
        public const ushort K_F38 = ((((ushort)KT_FN)<<8)|47);
        public const ushort K_F39 = ((((ushort)KT_FN)<<8)|48);
        public const ushort K_F40 = ((((ushort)KT_FN)<<8)|49);
        public const ushort K_F41 = ((((ushort)KT_FN)<<8)|50);
        public const ushort K_F42 = ((((ushort)KT_FN)<<8)|51);
        public const ushort K_F43 = ((((ushort)KT_FN)<<8)|52);
        public const ushort K_F44 = ((((ushort)KT_FN)<<8)|53);
        public const ushort K_F45 = ((((ushort)KT_FN)<<8)|54);
        public const ushort K_F46 = ((((ushort)KT_FN)<<8)|55);
        public const ushort K_F47 = ((((ushort)KT_FN)<<8)|56);
        public const ushort K_F48 = ((((ushort)KT_FN)<<8)|57);
        public const ushort K_F49 = ((((ushort)KT_FN)<<8)|58);
        public const ushort K_F50 = ((((ushort)KT_FN)<<8)|59);
        public const ushort K_F51 = ((((ushort)KT_FN)<<8)|60);
        public const ushort K_F52 = ((((ushort)KT_FN)<<8)|61);
        public const ushort K_F53 = ((((ushort)KT_FN)<<8)|62);
        public const ushort K_F54 = ((((ushort)KT_FN)<<8)|63);
        public const ushort K_F55 = ((((ushort)KT_FN)<<8)|64);
        public const ushort K_F56 = ((((ushort)KT_FN)<<8)|65);
        public const ushort K_F57 = ((((ushort)KT_FN)<<8)|66);
        public const ushort K_F58 = ((((ushort)KT_FN)<<8)|67);
        public const ushort K_F59 = ((((ushort)KT_FN)<<8)|68);
        public const ushort K_F60 = ((((ushort)KT_FN)<<8)|69);
        public const ushort K_F61 = ((((ushort)KT_FN)<<8)|70);
        public const ushort K_F62 = ((((ushort)KT_FN)<<8)|71);
        public const ushort K_F63 = ((((ushort)KT_FN)<<8)|72);
        public const ushort K_F64 = ((((ushort)KT_FN)<<8)|73);
        public const ushort K_F65 = ((((ushort)KT_FN)<<8)|74);
        public const ushort K_F66 = ((((ushort)KT_FN)<<8)|75);
        public const ushort K_F67 = ((((ushort)KT_FN)<<8)|76);
        public const ushort K_F68 = ((((ushort)KT_FN)<<8)|77);
        public const ushort K_F69 = ((((ushort)KT_FN)<<8)|78);
        public const ushort K_F70 = ((((ushort)KT_FN)<<8)|79);
        public const ushort K_F71 = ((((ushort)KT_FN)<<8)|80);
        public const ushort K_F72 = ((((ushort)KT_FN)<<8)|81);
        public const ushort K_F73 = ((((ushort)KT_FN)<<8)|82);
        public const ushort K_F74 = ((((ushort)KT_FN)<<8)|83);
        public const ushort K_F75 = ((((ushort)KT_FN)<<8)|84);
        public const ushort K_F76 = ((((ushort)KT_FN)<<8)|85);
        public const ushort K_F77 = ((((ushort)KT_FN)<<8)|86);
        public const ushort K_F78 = ((((ushort)KT_FN)<<8)|87);
        public const ushort K_F79 = ((((ushort)KT_FN)<<8)|88);
        public const ushort K_F80 = ((((ushort)KT_FN)<<8)|89);
        public const ushort K_F81 = ((((ushort)KT_FN)<<8)|90);
        public const ushort K_F82 = ((((ushort)KT_FN)<<8)|91);
        public const ushort K_F83 = ((((ushort)KT_FN)<<8)|92);
        public const ushort K_F84 = ((((ushort)KT_FN)<<8)|93);
        public const ushort K_F85 = ((((ushort)KT_FN)<<8)|94);
        public const ushort K_F86 = ((((ushort)KT_FN)<<8)|95);
        public const ushort K_F87 = ((((ushort)KT_FN)<<8)|96);
        public const ushort K_F88 = ((((ushort)KT_FN)<<8)|97);
        public const ushort K_F89 = ((((ushort)KT_FN)<<8)|98);
        public const ushort K_F90 = ((((ushort)KT_FN)<<8)|99);
        public const ushort K_F91 = ((((ushort)KT_FN)<<8)|100);
        public const ushort K_F92 = ((((ushort)KT_FN)<<8)|101);
        public const ushort K_F93 = ((((ushort)KT_FN)<<8)|102);
        public const ushort K_F94 = ((((ushort)KT_FN)<<8)|103);
        public const ushort K_F95 = ((((ushort)KT_FN)<<8)|104);
        public const ushort K_F96 = ((((ushort)KT_FN)<<8)|105);
        public const ushort K_F97 = ((((ushort)KT_FN)<<8)|106);
        public const ushort K_F98 = ((((ushort)KT_FN)<<8)|107);
        public const ushort K_F99 = ((((ushort)KT_FN)<<8)|108);
        public const ushort K_F100 = ((((ushort)KT_FN)<<8)|109);
        public const ushort K_F101 = ((((ushort)KT_FN)<<8)|110);
        public const ushort K_F102 = ((((ushort)KT_FN)<<8)|111);
        public const ushort K_F103 = ((((ushort)KT_FN)<<8)|112);
        public const ushort K_F104 = ((((ushort)KT_FN)<<8)|113);
        public const ushort K_F105 = ((((ushort)KT_FN)<<8)|114);
        public const ushort K_F106 = ((((ushort)KT_FN)<<8)|115);
        public const ushort K_F107 = ((((ushort)KT_FN)<<8)|116);
        public const ushort K_F108 = ((((ushort)KT_FN)<<8)|117);
        public const ushort K_F109 = ((((ushort)KT_FN)<<8)|118);
        public const ushort K_F110 = ((((ushort)KT_FN)<<8)|119);
        public const ushort K_F111 = ((((ushort)KT_FN)<<8)|120);
        public const ushort K_F112 = ((((ushort)KT_FN)<<8)|121);
        public const ushort K_F113 = ((((ushort)KT_FN)<<8)|122);
        public const ushort K_F114 = ((((ushort)KT_FN)<<8)|123);
        public const ushort K_F115 = ((((ushort)KT_FN)<<8)|124);
        public const ushort K_F116 = ((((ushort)KT_FN)<<8)|125);
        public const ushort K_F117 = ((((ushort)KT_FN)<<8)|126);
        public const ushort K_F118 = ((((ushort)KT_FN)<<8)|127);
        public const ushort K_F119 = ((((ushort)KT_FN)<<8)|128);
        public const ushort K_F120 = ((((ushort)KT_FN)<<8)|129);
        public const ushort K_F121 = ((((ushort)KT_FN)<<8)|130);
        public const ushort K_F122 = ((((ushort)KT_FN)<<8)|131);
        public const ushort K_F123 = ((((ushort)KT_FN)<<8)|132);
        public const ushort K_F124 = ((((ushort)KT_FN)<<8)|133);
        public const ushort K_F125 = ((((ushort)KT_FN)<<8)|134);
        public const ushort K_F126 = ((((ushort)KT_FN)<<8)|135);
        public const ushort K_F127 = ((((ushort)KT_FN)<<8)|136);
        public const ushort K_F128 = ((((ushort)KT_FN)<<8)|137);
        public const ushort K_F129 = ((((ushort)KT_FN)<<8)|138);
        public const ushort K_F130 = ((((ushort)KT_FN)<<8)|139);
        public const ushort K_F131 = ((((ushort)KT_FN)<<8)|140);
        public const ushort K_F132 = ((((ushort)KT_FN)<<8)|141);
        public const ushort K_F133 = ((((ushort)KT_FN)<<8)|142);
        public const ushort K_F134 = ((((ushort)KT_FN)<<8)|143);
        public const ushort K_F135 = ((((ushort)KT_FN)<<8)|144);
        public const ushort K_F136 = ((((ushort)KT_FN)<<8)|145);
        public const ushort K_F137 = ((((ushort)KT_FN)<<8)|146);
        public const ushort K_F138 = ((((ushort)KT_FN)<<8)|147);
        public const ushort K_F139 = ((((ushort)KT_FN)<<8)|148);
        public const ushort K_F140 = ((((ushort)KT_FN)<<8)|149);
        public const ushort K_F141 = ((((ushort)KT_FN)<<8)|150);
        public const ushort K_F142 = ((((ushort)KT_FN)<<8)|151);
        public const ushort K_F143 = ((((ushort)KT_FN)<<8)|152);
        public const ushort K_F144 = ((((ushort)KT_FN)<<8)|153);
        public const ushort K_F145 = ((((ushort)KT_FN)<<8)|154);
        public const ushort K_F146 = ((((ushort)KT_FN)<<8)|155);
        public const ushort K_F147 = ((((ushort)KT_FN)<<8)|156);
        public const ushort K_F148 = ((((ushort)KT_FN)<<8)|157);
        public const ushort K_F149 = ((((ushort)KT_FN)<<8)|158);
        public const ushort K_F150 = ((((ushort)KT_FN)<<8)|159);
        public const ushort K_F151 = ((((ushort)KT_FN)<<8)|160);
        public const ushort K_F152 = ((((ushort)KT_FN)<<8)|161);
        public const ushort K_F153 = ((((ushort)KT_FN)<<8)|162);
        public const ushort K_F154 = ((((ushort)KT_FN)<<8)|163);
        public const ushort K_F155 = ((((ushort)KT_FN)<<8)|164);
        public const ushort K_F156 = ((((ushort)KT_FN)<<8)|165);
        public const ushort K_F157 = ((((ushort)KT_FN)<<8)|166);
        public const ushort K_F158 = ((((ushort)KT_FN)<<8)|167);
        public const ushort K_F159 = ((((ushort)KT_FN)<<8)|168);
        public const ushort K_F160 = ((((ushort)KT_FN)<<8)|169);
        public const ushort K_F161 = ((((ushort)KT_FN)<<8)|170);
        public const ushort K_F162 = ((((ushort)KT_FN)<<8)|171);
        public const ushort K_F163 = ((((ushort)KT_FN)<<8)|172);
        public const ushort K_F164 = ((((ushort)KT_FN)<<8)|173);
        public const ushort K_F165 = ((((ushort)KT_FN)<<8)|174);
        public const ushort K_F166 = ((((ushort)KT_FN)<<8)|175);
        public const ushort K_F167 = ((((ushort)KT_FN)<<8)|176);
        public const ushort K_F168 = ((((ushort)KT_FN)<<8)|177);
        public const ushort K_F169 = ((((ushort)KT_FN)<<8)|178);
        public const ushort K_F170 = ((((ushort)KT_FN)<<8)|179);
        public const ushort K_F171 = ((((ushort)KT_FN)<<8)|180);
        public const ushort K_F172 = ((((ushort)KT_FN)<<8)|181);
        public const ushort K_F173 = ((((ushort)KT_FN)<<8)|182);
        public const ushort K_F174 = ((((ushort)KT_FN)<<8)|183);
        public const ushort K_F175 = ((((ushort)KT_FN)<<8)|184);
        public const ushort K_F176 = ((((ushort)KT_FN)<<8)|185);
        public const ushort K_F177 = ((((ushort)KT_FN)<<8)|186);
        public const ushort K_F178 = ((((ushort)KT_FN)<<8)|187);
        public const ushort K_F179 = ((((ushort)KT_FN)<<8)|188);
        public const ushort K_F180 = ((((ushort)KT_FN)<<8)|189);
        public const ushort K_F181 = ((((ushort)KT_FN)<<8)|190);
        public const ushort K_F182 = ((((ushort)KT_FN)<<8)|191);
        public const ushort K_F183 = ((((ushort)KT_FN)<<8)|192);
        public const ushort K_F184 = ((((ushort)KT_FN)<<8)|193);
        public const ushort K_F185 = ((((ushort)KT_FN)<<8)|194);
        public const ushort K_F186 = ((((ushort)KT_FN)<<8)|195);
        public const ushort K_F187 = ((((ushort)KT_FN)<<8)|196);
        public const ushort K_F188 = ((((ushort)KT_FN)<<8)|197);
        public const ushort K_F189 = ((((ushort)KT_FN)<<8)|198);
        public const ushort K_F190 = ((((ushort)KT_FN)<<8)|199);
        public const ushort K_F191 = ((((ushort)KT_FN)<<8)|200);
        public const ushort K_F192 = ((((ushort)KT_FN)<<8)|201);
        public const ushort K_F193 = ((((ushort)KT_FN)<<8)|202);
        public const ushort K_F194 = ((((ushort)KT_FN)<<8)|203);
        public const ushort K_F195 = ((((ushort)KT_FN)<<8)|204);
        public const ushort K_F196 = ((((ushort)KT_FN)<<8)|205);
        public const ushort K_F197 = ((((ushort)KT_FN)<<8)|206);
        public const ushort K_F198 = ((((ushort)KT_FN)<<8)|207);
        public const ushort K_F199 = ((((ushort)KT_FN)<<8)|208);
        public const ushort K_F200 = ((((ushort)KT_FN)<<8)|209);
        public const ushort K_F201 = ((((ushort)KT_FN)<<8)|210);
        public const ushort K_F202 = ((((ushort)KT_FN)<<8)|211);
        public const ushort K_F203 = ((((ushort)KT_FN)<<8)|212);
        public const ushort K_F204 = ((((ushort)KT_FN)<<8)|213);
        public const ushort K_F205 = ((((ushort)KT_FN)<<8)|214);
        public const ushort K_F206 = ((((ushort)KT_FN)<<8)|215);
        public const ushort K_F207 = ((((ushort)KT_FN)<<8)|216);
        public const ushort K_F208 = ((((ushort)KT_FN)<<8)|217);
        public const ushort K_F209 = ((((ushort)KT_FN)<<8)|218);
        public const ushort K_F210 = ((((ushort)KT_FN)<<8)|219);
        public const ushort K_F211 = ((((ushort)KT_FN)<<8)|220);
        public const ushort K_F212 = ((((ushort)KT_FN)<<8)|221);
        public const ushort K_F213 = ((((ushort)KT_FN)<<8)|222);
        public const ushort K_F214 = ((((ushort)KT_FN)<<8)|223);
        public const ushort K_F215 = ((((ushort)KT_FN)<<8)|224);
        public const ushort K_F216 = ((((ushort)KT_FN)<<8)|225);
        public const ushort K_F217 = ((((ushort)KT_FN)<<8)|226);
        public const ushort K_F218 = ((((ushort)KT_FN)<<8)|227);
        public const ushort K_F219 = ((((ushort)KT_FN)<<8)|228);
        public const ushort K_F220 = ((((ushort)KT_FN)<<8)|229);
        public const ushort K_F221 = ((((ushort)KT_FN)<<8)|230);
        public const ushort K_F222 = ((((ushort)KT_FN)<<8)|231);
        public const ushort K_F223 = ((((ushort)KT_FN)<<8)|232);
        public const ushort K_F224 = ((((ushort)KT_FN)<<8)|233);
        public const ushort K_F225 = ((((ushort)KT_FN)<<8)|234);
        public const ushort K_F226 = ((((ushort)KT_FN)<<8)|235);
        public const ushort K_F227 = ((((ushort)KT_FN)<<8)|236);
        public const ushort K_F228 = ((((ushort)KT_FN)<<8)|237);
        public const ushort K_F229 = ((((ushort)KT_FN)<<8)|238);
        public const ushort K_F230 = ((((ushort)KT_FN)<<8)|239);
        public const ushort K_F231 = ((((ushort)KT_FN)<<8)|240);
        public const ushort K_F232 = ((((ushort)KT_FN)<<8)|241);
        public const ushort K_F233 = ((((ushort)KT_FN)<<8)|242);
        public const ushort K_F234 = ((((ushort)KT_FN)<<8)|243);
        public const ushort K_F235 = ((((ushort)KT_FN)<<8)|244);
        public const ushort K_F236 = ((((ushort)KT_FN)<<8)|245);
        public const ushort K_F237 = ((((ushort)KT_FN)<<8)|246);
        public const ushort K_F238 = ((((ushort)KT_FN)<<8)|247);
        public const ushort K_F239 = ((((ushort)KT_FN)<<8)|248);
        public const ushort K_F240 = ((((ushort)KT_FN)<<8)|249);
        public const ushort K_F241 = ((((ushort)KT_FN)<<8)|250);
        public const ushort K_F242 = ((((ushort)KT_FN)<<8)|251);
        public const ushort K_F243 = ((((ushort)KT_FN)<<8)|252);
        public const ushort K_F244 = ((((ushort)KT_FN)<<8)|253);
        public const ushort K_F245 = ((((ushort)KT_FN)<<8)|254);
        public const ushort K_UNDO = ((((ushort)KT_FN)<<8)|255);


        public const ushort K_HOLE = ((((ushort)KT_SPEC)<<8)|0);
        public const ushort K_ENTER = ((((ushort)KT_SPEC)<<8)|1);
        public const ushort K_SH_REGS = ((((ushort)KT_SPEC)<<8)|2);
        public const ushort K_SH_MEM = ((((ushort)KT_SPEC)<<8)|3);
        public const ushort K_SH_STAT = ((((ushort)KT_SPEC)<<8)|4);
        public const ushort K_BREAK = ((((ushort)KT_SPEC)<<8)|5);
        public const ushort K_CONS = ((((ushort)KT_SPEC)<<8)|6);
        public const ushort K_CAPS = ((((ushort)KT_SPEC)<<8)|7);
        public const ushort K_NUM = ((((ushort)KT_SPEC)<<8)|8);
        public const ushort K_HOLD = ((((ushort)KT_SPEC)<<8)|9);
        public const ushort K_SCROLLFORW = ((((ushort)KT_SPEC)<<8)|10);
        public const ushort K_SCROLLBACK = ((((ushort)KT_SPEC)<<8)|11);
        public const ushort K_BOOT = ((((ushort)KT_SPEC)<<8)|12);
        public const ushort K_CAPSON = ((((ushort)KT_SPEC)<<8)|13);
        public const ushort K_COMPOSE = ((((ushort)KT_SPEC)<<8)|14);
        public const ushort K_SAK = ((((ushort)KT_SPEC)<<8)|15);
        public const ushort K_DECRCONSOLE = ((((ushort)KT_SPEC)<<8)|16);
        public const ushort K_INCRCONSOLE = ((((ushort)KT_SPEC)<<8)|17);
        public const ushort K_SPAWNCONSOLE = ((((ushort)KT_SPEC)<<8)|18);
        public const ushort K_BARENUMLOCK = ((((ushort)KT_SPEC)<<8)|19);

        public const ushort K_ALLOCATED = ((((ushort)KT_SPEC)<<8)|126); /* dynamically allocated keymap */
        public const ushort K_NOSUCHMAP = ((((ushort)KT_SPEC)<<8)|127); /* returned by KDGKBENT */

        public const ushort K_P0 = ((((ushort)KT_PAD)<<8)|0);
        public const ushort K_P1 = ((((ushort)KT_PAD)<<8)|1);
        public const ushort K_P2 = ((((ushort)KT_PAD)<<8)|2);
        public const ushort K_P3 = ((((ushort)KT_PAD)<<8)|3);
        public const ushort K_P4 = ((((ushort)KT_PAD)<<8)|4);
        public const ushort K_P5 = ((((ushort)KT_PAD)<<8)|5);
        public const ushort K_P6 = ((((ushort)KT_PAD)<<8)|6);
        public const ushort K_P7 = ((((ushort)KT_PAD)<<8)|7);
        public const ushort K_P8 = ((((ushort)KT_PAD)<<8)|8);
        public const ushort K_P9 = ((((ushort)KT_PAD)<<8)|9);
        public const ushort K_PPLUS = ((((ushort)KT_PAD)<<8)|10); /* key-pad plus */
        public const ushort K_PMINUS = ((((ushort)KT_PAD)<<8)|11); /* key-pad minus */
        public const ushort K_PSTAR = ((((ushort)KT_PAD)<<8)|12); /* key-pad asterisk (star) */
        public const ushort K_PSLASH = ((((ushort)KT_PAD)<<8)|13); /* key-pad slash */
        public const ushort K_PENTER = ((((ushort)KT_PAD)<<8)|14); /* key-pad enter */
        public const ushort K_PCOMMA = ((((ushort)KT_PAD)<<8)|15); /* key-pad comma: kludge... */
        public const ushort K_PDOT = ((((ushort)KT_PAD)<<8)|16); /* key-pad dot (period): kludge... */
        public const ushort K_PPLUSMINUS = ((((ushort)KT_PAD)<<8)|17); /* key-pad plus/minus */
        public const ushort K_PPARENL = ((((ushort)KT_PAD)<<8)|18); /* key-pad left parenthesis */
        public const ushort K_PPARENR = ((((ushort)KT_PAD)<<8)|19); /* key-pad right parenthesis */

        public const byte NR_PAD = 20;

        public const ushort K_DGRAVE = ((((ushort)KT_DEAD)<<8)|0);
        public const ushort K_DACUTE = ((((ushort)KT_DEAD)<<8)|1);
        public const ushort K_DCIRCM = ((((ushort)KT_DEAD)<<8)|2);
        public const ushort K_DTILDE = ((((ushort)KT_DEAD)<<8)|3);
        public const ushort K_DDIERE = ((((ushort)KT_DEAD)<<8)|4);
        public const ushort K_DCEDIL = ((((ushort)KT_DEAD)<<8)|5);
        public const ushort K_DMACRON = ((((ushort)KT_DEAD)<<8)|6);
        public const ushort K_DBREVE = ((((ushort)KT_DEAD)<<8)|7);
        public const ushort K_DABDOT = ((((ushort)KT_DEAD)<<8)|8);
        public const ushort K_DABRING = ((((ushort)KT_DEAD)<<8)|9);
        public const ushort K_DDBACUTE = ((((ushort)KT_DEAD)<<8)|10);
        public const ushort K_DCARON = ((((ushort)KT_DEAD)<<8)|11);
        public const ushort K_DOGONEK = ((((ushort)KT_DEAD)<<8)|12);
        public const ushort K_DIOTA = ((((ushort)KT_DEAD)<<8)|13);
        public const ushort K_DVOICED = ((((ushort)KT_DEAD)<<8)|14);
        public const ushort K_DSEMVOICED = ((((ushort)KT_DEAD)<<8)|15);
        public const ushort K_DBEDOT = ((((ushort)KT_DEAD)<<8)|16);
        public const ushort K_DHOOK = ((((ushort)KT_DEAD)<<8)|17);
        public const ushort K_DHORN = ((((ushort)KT_DEAD)<<8)|18);
        public const ushort K_DSTROKE = ((((ushort)KT_DEAD)<<8)|19);
        public const ushort K_DABCOMMA = ((((ushort)KT_DEAD)<<8)|20);
        public const ushort K_DABREVCOMMA = ((((ushort)KT_DEAD)<<8)|21);
        public const ushort K_DDBGRAVE = ((((ushort)KT_DEAD)<<8)|22);
        public const ushort K_DINVBREVE = ((((ushort)KT_DEAD)<<8)|23);
        public const ushort K_DBECOMMA = ((((ushort)KT_DEAD)<<8)|24);
        public const ushort K_DCURRENCY = ((((ushort)KT_DEAD)<<8)|25);
        public const ushort K_DGREEK = ((((ushort)KT_DEAD)<<8)|26);

        public const byte NR_DEAD = 27;

        public const ushort K_DOWN = ((((ushort)KT_CUR)<<8)|0);
        public const ushort K_LEFT = ((((ushort)KT_CUR)<<8)|1);
        public const ushort K_RIGHT = ((((ushort)KT_CUR)<<8)|2);
        public const ushort K_UP = ((((ushort)KT_CUR)<<8)|3);

        public const ushort K_SHIFT = ((((ushort)KT_CUR)<<8)|KG_SHIFT);
        public const ushort K_CTRL = ((((ushort)KT_CUR)<<8)|KG_CTRL);
        public const ushort K_ALT = ((((ushort)KT_CUR)<<8)|KG_ALT);
        public const ushort K_ALTGR = ((((ushort)KT_CUR)<<8)|KG_ALTGR);
        public const ushort K_SHIFTL = ((((ushort)KT_CUR)<<8)|KG_SHIFTL);
        public const ushort K_SHIFTR = ((((ushort)KT_CUR)<<8)|KG_SHIFTR);
        public const ushort K_CTRLL  = ((((ushort)KT_CUR)<<8)|KG_CTRLL);
        public const ushort K_CTRLR  = ((((ushort)KT_CUR)<<8)|KG_CTRLR);
        public const ushort K_CAPSSHIFT = ((((ushort)KT_CUR)<<8)|KG_CAPSSHIFT);

        public const ushort K_ASC0 = ((((ushort)KT_ASCII)<<8)|0);
        public const ushort K_ASC1 = ((((ushort)KT_ASCII)<<8)|1);
        public const ushort K_ASC2 = ((((ushort)KT_ASCII)<<8)|2);
        public const ushort K_ASC3 = ((((ushort)KT_ASCII)<<8)|3);
        public const ushort K_ASC4 = ((((ushort)KT_ASCII)<<8)|4);
        public const ushort K_ASC5 = ((((ushort)KT_ASCII)<<8)|5);
        public const ushort K_ASC6 = ((((ushort)KT_ASCII)<<8)|6);
        public const ushort K_ASC7 = ((((ushort)KT_ASCII)<<8)|7);
        public const ushort K_ASC8 = ((((ushort)KT_ASCII)<<8)|8);
        public const ushort K_ASC9 = ((((ushort)KT_ASCII)<<8)|9);
        public const ushort K_HEX0 = ((((ushort)KT_ASCII)<<8)|10);
        public const ushort K_HEX1 = ((((ushort)KT_ASCII)<<8)|11);
        public const ushort K_HEX2 = ((((ushort)KT_ASCII)<<8)|12);
        public const ushort K_HEX3 = ((((ushort)KT_ASCII)<<8)|13);
        public const ushort K_HEX4 = ((((ushort)KT_ASCII)<<8)|14);
        public const ushort K_HEX5 = ((((ushort)KT_ASCII)<<8)|15);
        public const ushort K_HEX6 = ((((ushort)KT_ASCII)<<8)|16);
        public const ushort K_HEX7 = ((((ushort)KT_ASCII)<<8)|17);
        public const ushort K_HEX8 = ((((ushort)KT_ASCII)<<8)|18);
        public const ushort K_HEX9 = ((((ushort)KT_ASCII)<<8)|19);
        public const ushort K_HEXa = ((((ushort)KT_ASCII)<<8)|20);
        public const ushort K_HEXb = ((((ushort)KT_ASCII)<<8)|21);
        public const ushort K_HEXc = ((((ushort)KT_ASCII)<<8)|22);
        public const ushort K_HEXd = ((((ushort)KT_ASCII)<<8)|23);
        public const ushort K_HEXe = ((((ushort)KT_ASCII)<<8)|24);
        public const ushort K_HEXf = ((((ushort)KT_ASCII)<<8)|25);

        public const byte NR_ASCII = 26;

        public const ushort K_SHIFTLOCK = ((((ushort)KT_LOCK)<<8)|KG_SHIFT);
        public const ushort K_CTRLLOCK = ((((ushort)KT_LOCK)<<8)|KG_CTRL);
        public const ushort K_ALTLOCK = ((((ushort)KT_LOCK)<<8)|KG_ALT);
        public const ushort K_ALTGRLOCK = ((((ushort)KT_LOCK)<<8)|KG_ALTGR);
        public const ushort K_SHIFTLLOCK = ((((ushort)KT_LOCK)<<8)|KG_SHIFTL);
        public const ushort K_SHIFTRLOCK = ((((ushort)KT_LOCK)<<8)|KG_SHIFTR);
        public const ushort K_CTRLLLOCK = ((((ushort)KT_LOCK)<<8)|KG_CTRLL);
        public const ushort K_CTRLRLOCK = ((((ushort)KT_LOCK)<<8)|KG_CTRLR);
        public const ushort K_CAPSSHIFTLOCK = ((((ushort)KT_LOCK)<<8)|KG_CAPSSHIFT);

        public const ushort K_SHIFT_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_SHIFT);
        public const ushort K_CTRL_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_CTRL);
        public const ushort K_ALT_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_ALT);
        public const ushort K_ALTGR_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_ALTGR);
        public const ushort K_SHIFTL_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_SHIFTL);
        public const ushort K_SHIFTR_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_SHIFTR);
        public const ushort K_CTRLL_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_CTRLL);
        public const ushort K_CTRLR_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_CTRLR);
        public const ushort K_CAPSSHIFT_SLOCK = ((((ushort)KT_SLOCK)<<8)|KG_CAPSSHIFT);

        public const ushort NR_LOCK = 9;

        public const ushort K_BRL_BLANK= ((((ushort)KT_BRL)<<8)| 0);
        public const ushort K_BRL_DOT1 = ((((ushort)KT_BRL)<<8)| 1);
        public const ushort K_BRL_DOT2 = ((((ushort)KT_BRL)<<8)| 2);
        public const ushort K_BRL_DOT3 = ((((ushort)KT_BRL)<<8)| 3);
        public const ushort K_BRL_DOT4 = ((((ushort)KT_BRL)<<8)| 4);
        public const ushort K_BRL_DOT5 = ((((ushort)KT_BRL)<<8)| 5);
        public const ushort K_BRL_DOT6 = ((((ushort)KT_BRL)<<8)| 6);
        public const ushort K_BRL_DOT7 = ((((ushort)KT_BRL)<<8)| 7);
        public const ushort K_BRL_DOT8 = ((((ushort)KT_BRL)<<8)| 8);
        public const ushort K_BRL_DOT9 = ((((ushort)KT_BRL)<<8)| 9);
        public const ushort K_BRL_DOT10 = ((((ushort)KT_BRL)<<8)| 10);

        public const byte NR_BRL = 11;

        public const ushort MAX_DIACR = 256;
    }
#pragma warning disable CS8981
}
#endif