name: Build & Upload Binaries

on:
  push:
    branches:
      - '**'

jobs:
  build-macos-arm64:
    permissions:
      contents: read
    name: Build program using Arm64 MacOS
    runs-on: macos-15
    steps:
      - name: Test MacOS Version
        shell: bash
        run: sw_vers -productVersion | cut -d '.' -f 1,2
  
  build-macos-x64:
    permissions:
      contents: read
    name: Build program using x64 MacOS 13
    runs-on: macos-13=
    steps:
      - name: Test MacOS Version
        shell: bash
        run: sw_vers -productVersion | cut -d '.' -f 1,2
  
  build-macos-docker-x64:
    permissions:
      contents: read
    name: Build program using x64 MacOS 15 (Docker)
    runs-on: ubuntu-latest
    container:
      image: dockurr/macos
      env:
        VERSION: "15"
    
    steps:
      - name: Test MacOS Version
        shell: bash
        run: sw_vers -productVersion | cut -d '.' -f 1,2
