name: Upload Binaries

on:
  push:
    branches:
      - main

jobs:
  build-msys:
    name: Build program using MSYS2
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
      - name: Install Programs
        shell: msys2 {0}
        run: |
          echo \nY > yes.in
          pacman -S make < yes.in
          pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain < yes.in
          rm yes.in
      - name: get verisons
        shell: msys2 {0}
        run: |
          make -v
          g++ -v
          uname -a
      - name: Compile code
        shell: msys2 {0}
        run: |
          make release sudo=0
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: Msys2CppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: Msys2CsBin
          path: bin/*C#*
  
  build-windows:
    name: Build program using Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Programs
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://deac-fra.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip?viasf=1" -OutFile "make-binaries.zip" -Verbose
          Expand-Archive -Force make-binaries.zip make-bin
          del make-binaries.zip
          move make\bin\make.exe .
          rmdir /s make-bin
      - name: get verisons
        shell: cmd
        run: |
          make -v
          g++ -v
          uname -a
      - name: Compile code
        shell: cmd
        run: |
          make release sudo=0
          
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
