name: Download & Release Binaries

on:
  push:
    tags:
      - v*.*-zeta
      - v*.*.*-zeta
      - v*.*.*-alpha
      - v*.*-alpha
      - v*.*.*-alpha
      - v*.*-beta
      - v*.*.*-beta
      - v*.*
      - v*.*.*

jobs:
  release:
    name: Release Compiled Binaries and Source Code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout last commit
        uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: stas-badzi
          repo: c-c-collab
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: Release ${{ steps.vars.outputs.tag }}
          body_path: Release.md
          draft: false
          prerelease: false
      - name: Clean Files
        run: rm -rf *

      - name: Download MacOSArmCppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: MacOSArmCppBin
          path: .
      - name: Get Name of MacOSArmCppBin
        shell: sh
        id: macos-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload MacOSArmCppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.macos-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.macos-cpp-bin-name.outputs.path }}
          asset_content_type: application/x-tar
      - name: Clean MacOSAmdCppBin
        shell: sh
        run: rm -rf *
        
      - name: Download MacOSx64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: MacOSAmdCppBin
          path: .
      - name: Get Name of MacOSAmdCppBin
        shell: sh
        id: macosx64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload MacOSAmdCppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.macosx64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.macosx64-cpp-bin-name.outputs.path }}
          asset_content_type: application/x-tar
      - name: Clean MacOSAmdCppBin
        shell: sh
        run: rm -rf *
        
      - name: Download MacOSUniversal2CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: MacOSUniversal2CppBin
          path: .
      - name: Get Name of MacOSUniversal2CppBin
        shell: sh
        id: macos-universal2-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload MacOSUniversal2CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.macos-universal2-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.macos-universal2-cpp-bin-name.outputs.path }}
          asset_content_type: application/x-tar
      - name: Clean MacOSUniversal2CppBin
        shell: sh
        run: rm -rf *

      - name: Download Ubuntux64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Ubuntux64CppBin
          path: .
      - name: Get Name of Ubuntux64CppBin
        shell: sh
        id: ubuntux64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Ubuntux64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.ubuntux64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.ubuntux64-cpp-bin-name.outputs.path }}
          asset_content_type: application/x-tar
      - name: Clean Ubuntux64CppBin
        shell: sh
        run: rm -rf *

      - name: Download UbuntuArm64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: UbuntuArm64CppBin
          path: .
      - name: Get Name of UbuntuArm64CppBin
        shell: sh
        id: ubuntuarm64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload UbuntuArm64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.ubuntuarm64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.ubuntuarm64-cpp-bin-name.outputs.path }}
          asset_content_type: application/x-tar
      - name: Clean UbuntuArm64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Windowsx64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Windowsx64CppBin
          path: .
      - name: Get Name of Windowsx64CppBin
        shell: sh
        id: winx64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Windowsx64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.winx64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.winx64-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Windowsx64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Windowsx86CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Windowsx86CppBin
          path: .
      - name: Get Name of Windowsx86CppBin
        shell: sh
        id: winx86-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Windowsx86CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.winx86-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.winx86-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Windowsx86CppBin
        shell: sh
        run: rm -rf *

      - name: Download Windowsarm64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Windowsarm64CppBin
          path: .
      - name: Get Name of Windowsarm64CppBin
        shell: sh
        id: winarm64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Windowsarm64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.winarm64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.winarm64-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Windowsarm64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Windowsarm32CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Windowsarm32CppBin
          path: .
      - name: Get Name of Windowsarm32CppBin
        shell: sh
        id: winarm32-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Windowsarm32CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.winarm32-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.winarm32-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Windowsarm32CppBin
        shell: sh
        run: rm -rf *

      - name: Download Msys2x64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Msys2x64CppBin
          path: .
      - name: Get Name of Msys2x64CppBin
        shell: sh
        id: msysx64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Msys2x64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.msysx64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.msysx64-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Msys2x64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Msys2i686CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Msys2i686CppBin
          path: .
      - name: Get Name of Msys2i686CppBin
        shell: sh
        id: msysi686-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Msys2i686CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.msysi686-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.msysi686-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Msys2i686CppBin
        shell: sh
        run: rm -rf *

      - name: Download Msys2aarch64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Msys2aarch64CppBin
          path: .
      - name: Get Name of Msys2aarch64CppBin
        shell: sh
        id: msysaarch64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Msys2aarch64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.msysaarch64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.msysaarch64-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Msys2aarch64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Cygwinx64CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Cygwinx64CppBin
          path: .
      - name: Get Name of Cygwinx64CppBin
        shell: sh
        id: cygwinx64-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Cygwinx64CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.cygwinx64-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.cygwinx64-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Cygwinx64CppBin
        shell: sh
        run: rm -rf *

      - name: Download Cygwinx86CppBin
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: Cygwinx86CppBin
          path: .
      - name: Get Name of Cygwinx86CppBin
        shell: sh
        id: cygwinx86-cpp-bin-name
        run: "echo path=$(ls) >> $GITHUB_OUTPUT"
      - name: Upload Cygwinx86CppBin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.cygwinx86-cpp-bin-name.outputs.path }}
          asset_name: ${{ steps.cygwinx86-cpp-bin-name.outputs.path }}
          asset_content_type: application/zip
      - name: Clean Cygwinx86CppBin
        shell: sh
        run: rm -rf *