name: Upload Binaries

on:
  push:

jobs:
  build-windows:
    name: Build program for windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Programs
        run: |
          C:/msys64/msys2.exe pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain 
          C:/msys64/msys2.exe pacman -S sudo
          C:/msys64/mingw64.exe sudo touch a.txt
          dir
          

      - name: Compile code
        run: |
          make
      - name: output
        run: |
          cd D:\
          dir
          type D:\out.log
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
