name: Download & Publish Binaries

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  release:
    name: Release Program
    runs-on: macos-latest
    steps:
      - name: Compress MacOS
        shell: bash
        run: |
          cd ..
          tar 

  