name: Upload Binaries

on:
  push:

jobs:
  build-windows:
    name: Build program for windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Programs
        run: choco install gsudo && echo $PATH && choco list && cd C:\tools\gsudo && ls && C:\msys64\mingw64.exe export PATH=/c/tools/gsudo/Latest:$PATH && C:\msys64\mingw64.exe echo $PATH
      - name: Compile code
        run: make
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
