name: Upload Binaries

on:
  push:
    branches:
      - main

jobs:
  build-msys:
    name: Build program using MSYS2
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
          

      - name: Compile code
        run: |
          make release sudo=0
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
  
  build-windows:
    name: Build program using Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Programs
        shell: pwshs
        run: |
          wget -Uri "https://downloads.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip?ts=gAAAAABmmED3vfP-Z6dPi2gnspGbYmi-W1HZ3TzET40Wj4yjVg2mQfFjUPxQ3Zo9NzVGjYsp1bA15kKuq8loWjIeUZaNOws31w%3D%3D&use_mirror=altushost-swe&r=" -OutFile "make-binaries.zip" -Verbose
          unzip make-binaries.zip make
          del /f make-3.81-bin.zip
          move make\bin\make.exe .
          rmdir /f make

      - name: Compile code
        shell: cmd
        run: |
          make.exe release sudo=0
          
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
