name: Download & Release Binaries

on:
  push:
    tags:
      - v*.*-zeta
      - v*.*.*-zeta
      - v*.*.*-alpha
      - v*.*-alpha
      - v*.*.*-alpha
      - v*.*-beta
      - v*.*.*-beta
      - v*.*
      - v*.*.*

jobs:
  compress-source:
    name: Compress and Upload Source Code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Compress Source for MacOS
        shell: bash
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          cd ..
          mv c-c-collab c-c-collab-$RELEASE_VERSION
          tar -czvf "Source Code.tgz" c-c-collab-*
      - name: Upload compressed source code
        uses: actions/upload-artifact@v4
        with:
          name: MacOSSourceCode
          path: "Source Code.tgz"

  release:
    name: Release Compiled Binaries and Source Code
    runs-on: ubuntu-latest
    needs: compress-source
    steps:
      - name: Clean Files
        run: |
          cd ..
          rm -rf .
      - name: Download MacOS Compressed Source Code
        uses: actions/download-artifact@v4
        with:
          path: $(pwd)
          name: MacOSSourceCode
      - name: Download Binaries
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          name: MacOSCppBin
          path: .


  