name: Upload Binaries

on:
  push:

jobs:
  build-windows:
    name: Build program for windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Programs
        run: |
          choco install gsudo
          C:/msys64/mingw64.exe alias sudo="/c/tools/gsudo/Current/gsudo.exe"
          

      - name: Compile code
        run: |
          C:/msys64/mingw64.exe hkhhk
      - name: Upload C++ binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCppBin
          path: bin/*C++*
      - name: Upload C# binaries
        uses: actions/upload-artifact@v4
        with:
          name: WindowsCsBin
          path: bin/*C#*
